[package]
name = "Barium-lexer"
version = "0.1.0"
edition = "2024"

keywords = ["lexer", "token"]
description = "Simple lexer written in Rust"
readme = "README.md"

[dependencies]
colored = "3.1.1"

[lib]
name="barium"
crate-type = ["rlib"]


[[test]]
name = "main"
path = ".ignore/tests/main.rs"
harness = true
